name: Run text_processor.py

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 6 * * *'  # Runs every day at 6:30 AM UTC

jobs:
  run-text-processor:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv lxml langdetect
          
      # Step 4: Run text_processor.py
      - name: Run text_processor.py
        run: python text_processor.py

      # Step 5: Commit and push updated scraped URLs
      - name: Commit and push updated scraped URLs
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add scraped_urls.json
          git commit -m "Update scraped URLs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

