name: Run text_processor.py

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-text-processor:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv lxml langdetect
          
      # Step 4: Run text_processor.py
      - name: Run text_processor.py
        run: python text_processor.py
