name: Run text_processor.py

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 6-18/4 * * *'   # Runs every day 6 times

jobs:
  run-text-processor:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv lxml langdetect
          pip install pillow  # Explicitly install Pillow          
      # Step 4: Run text_processor.py
      - name: Run text_processor.py
        run: python text_processor.py

      # Step 5: Commit and push updated URLs data
      - name: Commit and push updated URLs data
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add urls_data.json
          git commit -m "Update scraped URLs data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
